/*
 * This source file was generated by the Gradle 'init' task
 */
package rubrica;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Rubrica classUnderTest = new Rubrica();
    }
}
